name: Go Server CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs
jobs:
  # Test job
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3

    # Setup Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Install dependencies
    - name: Install dependencies
      run: go mod download

    # Run tests
    - name: Run tests
      run: go test -v ./...

    # Optional: Run golangci-lint
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
